# Generated by Django 3.2.8 on 2021-10-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('project_time', models.DateTimeField()),
                ('ex_online_time', models.DateTimeField()),
                ('ac_online_time', models.DateTimeField()),
                ('sales_price', models.DecimalField(decimal_places=6, max_digits=24)),
                ('development_cost', models.DecimalField(decimal_places=6, max_digits=24)),
                ('project_status', models.CharField(max_length=32)),
                ('quality_status', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('amount_collected', models.CharField(max_length=255)),
                ('amount_uncollected', models.CharField(max_length=255)),
                ('payment_process', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_ip', models.GenericIPAddressField()),
                ('server_domain', models.CharField(max_length=255)),
                ('server_belong', models.CharField(choices=[('公司', '公司'), ('省联社', '省联社'), ('其他', '其他')], max_length=255)),
                ('server_type', models.CharField(choices=[('数据服务器', '数据服务器'), ('应用服务器', '应用服务器'), ('综合服务器', '综合服务器')], max_length=255)),
                ('server_system', models.CharField(choices=[('WINDOWS', 'WINDOWS'), ('LINUX', 'LINUX')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_period', models.CharField(max_length=255)),
                ('quality_people', models.CharField(max_length=255)),
                ('quality_money', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pmapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(to='pmapp.Server'),
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_periods', models.IntegerField()),
                ('payee', models.CharField(max_length=255)),
                ('current_collection', models.DecimalField(decimal_places=6, max_digits=24)),
                ('receipt_date', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pmapp.project')),
            ],
        ),
    ]
