# Generated by Django 3.2.9 on 2021-12-06 06:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('project_time', models.DateField()),
                ('ex_online_time', models.DateField()),
                ('ac_online_time', models.DateField()),
                ('sales_price', models.DecimalField(decimal_places=6, max_digits=24)),
                ('development_cost', models.DecimalField(decimal_places=6, max_digits=24)),
                ('project_status', models.CharField(choices=[('立项', '立项'), ('上线', '上线'), ('下线', '下线')], max_length=32)),
                ('quality_status', models.CharField(choices=[('即将过期', '即将过期'), ('已过期', '已过期'), ('质保中', '质保中')], default='质保中', max_length=255)),
                ('payment_status', models.CharField(choices=[('收款中', '收款中'), ('已收款', '已收款'), ('待收款', '待收款')], default='待收款', max_length=255)),
                ('amount_collected', models.IntegerField(default=0)),
                ('amount_uncollected', models.IntegerField(default=0)),
                ('payment_process', models.IntegerField(default=0)),
                ('project_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_ip', models.GenericIPAddressField()),
                ('server_domain', models.CharField(max_length=255)),
                ('server_belong', models.CharField(choices=[('公司', '公司'), ('省联社', '省联社'), ('其他', '其他')], max_length=255)),
                ('server_type', models.CharField(choices=[('数据服务器', '数据服务器'), ('应用服务器', '应用服务器'), ('综合服务器', '综合服务器')], max_length=255)),
                ('server_system', models.CharField(choices=[('WINDOWS', 'WINDOWS'), ('LINUX', 'LINUX')], max_length=255)),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器管理',
            },
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_period', models.CharField(max_length=255)),
                ('quality_money', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pmapp.project')),
                ('quality_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '质保记录',
                'verbose_name_plural': '质保记录管理',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ManyToManyField(to='pmapp.Server'),
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_periods', models.IntegerField()),
                ('current_collection', models.DecimalField(decimal_places=6, max_digits=24)),
                ('receipt_date', models.DateField()),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pmapp.project')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录管理',
            },
        ),
    ]
