# Generated by Django 3.2.9 on 2021-12-16 07:04

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('redirect', models.CharField(max_length=255)),
                ('always_show', models.CharField(max_length=255)),
                ('keep_alive', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('menu', models.ManyToManyField(to='pmapp.Menu')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
