# Generated by Django 3.2.8 on 2021-10-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmapp', '0002_auto_20211020_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
