# Generated by Django 3.2.8 on 2021-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0004_auto_20211020_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrecord',
            name='receipt_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='ac_online_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='ex_online_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualityrecord',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='qualityrecord',
            name='start_date',
            field=models.DateField(),
        ),
    ]
